package Agilecrm.apiAutomatiion;

import org.apache.commons.lang3.RandomStringUtils;
import org.json.JSONObject;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;

public class VerifyContentApi {

	public static void main(String[] args) {
		
		String  RandomEmail=RandomStringUtils.randomAlphanumeric(20)+"@gmail.com";
		String  ContactJson ="[\r\n"
				+ "    {\r\n"
				+ "        \"id\": 4769399745216512,\r\n"
				+ "        \"type\": \"PERSON\",\r\n"
				+ "        \"created_time\": 1762490960,\r\n"
				+ "        \"updated_time\": 0,\r\n"
				+ "        \"last_contacted\": 0,\r\n"
				+ "        \"last_emailed\": 0,\r\n"
				+ "        \"last_campaign_emaild\": 0,\r\n"
				+ "        \"last_called\": 0,\r\n"
				+ "        \"viewed_time\": 0,\r\n"
				+ "        \"viewed\": {\r\n"
				+ "            \"viewed_time\": 0\r\n"
				+ "        },\r\n"
				+ "        \"star_value\": 5,\r\n"
				+ "        \"lead_score\": 125,\r\n"
				+ "        \"klout_score\": \"\",\r\n"
				+ "        \"tags\": [\r\n"
				+ "            \"Sample\"\r\n"
				+ "        ],\r\n"
				+ "        \"tagsWithTime\": [\r\n"
				+ "            {\r\n"
				+ "                \"tag\": \"Sample\",\r\n"
				+ "                \"createdTime\": 1762490960159,\r\n"
				+ "                \"availableCount\": 0,\r\n"
				+ "                \"entity_type\": \"tag\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"properties\": [\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"first_name\",\r\n"
				+ "                \"value\": \"Customer Success\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"last_name\",\r\n"
				+ "                \"value\": \"Team\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"company\",\r\n"
				+ "                \"value\": \"Agile CRM\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"title\",\r\n"
				+ "                \"value\": \"Support\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"website\",\r\n"
				+ "                \"subtype\": \"URL\",\r\n"
				+ "                \"value\": \"http://www.agilecrm.com\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"address\",\r\n"
				+ "                \"subtype\": \"work\",\r\n"
				+ "                \"value\": \"{\\\"country\\\":\\\"US\\\",\\\"city\\\":\\\"Dallas\\\",\\\"countryname\\\":\\\"United States\\\",\\\"state\\\":\\\"Texas\\\"}\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"image\",\r\n"
				+ "                \"value\": \"https://www.agilecrm.com/icons/service.svg\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"campaignStatus\": [],\r\n"
				+ "        \"entity_type\": \"contact_entity\",\r\n"
				+ "        \"contact_company_id\": \"5915161862537216\",\r\n"
				+ "        \"unsubscribeStatus\": [],\r\n"
				+ "        \"emailBounceStatus\": [],\r\n"
				+ "        \"formId\": 0,\r\n"
				+ "        \"browserId\": [],\r\n"
				+ "        \"lead_source_id\": 0,\r\n"
				+ "        \"lead_status_id\": 0,\r\n"
				+ "        \"is_lead_converted\": false,\r\n"
				+ "        \"lead_converted_time\": 0,\r\n"
				+ "        \"is_duplicate_existed\": false,\r\n"
				+ "        \"trashed_time\": 0,\r\n"
				+ "        \"restored_time\": 0,\r\n"
				+ "        \"is_duplicate_verification_failed\": false,\r\n"
				+ "        \"is_client_import\": false,\r\n"
				+ "        \"concurrent_save_allowed\": true,\r\n"
				+ "        \"owner\": {\r\n"
				+ "            \"id\": 6621248345538560,\r\n"
				+ "            \"domain\": \"yadavshubham4567\",\r\n"
				+ "            \"email\": \"yadavshubham@eva.com\",\r\n"
				+ "            \"phone\": \"\",\r\n"
				+ "            \"name\": \"Shubham\",\r\n"
				+ "            \"pic\": \"https://d1gwclp1pmzk26.cloudfront.net/img/gravatar/48.png\",\r\n"
				+ "            \"schedule_id\": \"Shubham\",\r\n"
				+ "            \"calendar_url\": \"https://yadavshubham4567.agilecrm.com/calendar/Shubham\",\r\n"
				+ "            \"calendarURL\": \"https://yadavshubham4567.agilecrm.com/calendar/Shubham\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 5339015487881216,\r\n"
				+ "        \"type\": \"PERSON\",\r\n"
				+ "        \"created_time\": 1762512269,\r\n"
				+ "        \"updated_time\": 0,\r\n"
				+ "        \"last_contacted\": 0,\r\n"
				+ "        \"last_emailed\": 0,\r\n"
				+ "        \"last_campaign_emaild\": 0,\r\n"
				+ "        \"last_called\": 0,\r\n"
				+ "        \"viewed_time\": 0,\r\n"
				+ "        \"viewed\": {\r\n"
				+ "            \"viewed_time\": 1762512280595,\r\n"
				+ "            \"viewer_id\": 6621248345538560\r\n"
				+ "        },\r\n"
				+ "        \"star_value\": 0,\r\n"
				+ "        \"lead_score\": 0,\r\n"
				+ "        \"klout_score\": \"\",\r\n"
				+ "        \"tags\": [\r\n"
				+ "            \"runmachine\"\r\n"
				+ "        ],\r\n"
				+ "        \"tagsWithTime\": [\r\n"
				+ "            {\r\n"
				+ "                \"tag\": \"runmachine\",\r\n"
				+ "                \"createdTime\": 1762512269073,\r\n"
				+ "                \"availableCount\": 0,\r\n"
				+ "                \"entity_type\": \"tag\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"properties\": [\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"first_name\",\r\n"
				+ "                \"value\": \"Virat\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"last_name\",\r\n"
				+ "                \"value\": \"kohli\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"company\",\r\n"
				+ "                \"value\": \"bcci\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"email\",\r\n"
				+ "                \"value\": \"viratkohli@gmail.com\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"phone\",\r\n"
				+ "                \"value\": \"7654323456\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"title\",\r\n"
				+ "                \"value\": \"batsman\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"campaignStatus\": [],\r\n"
				+ "        \"entity_type\": \"contact_entity\",\r\n"
				+ "        \"source\": \"manual\",\r\n"
				+ "        \"contact_company_id\": \"6272729298436096\",\r\n"
				+ "        \"unsubscribeStatus\": [],\r\n"
				+ "        \"emailBounceStatus\": [],\r\n"
				+ "        \"formId\": 0,\r\n"
				+ "        \"browserId\": [],\r\n"
				+ "        \"lead_source_id\": 0,\r\n"
				+ "        \"lead_status_id\": 0,\r\n"
				+ "        \"is_lead_converted\": false,\r\n"
				+ "        \"lead_converted_time\": 0,\r\n"
				+ "        \"is_duplicate_existed\": false,\r\n"
				+ "        \"trashed_time\": 0,\r\n"
				+ "        \"restored_time\": 0,\r\n"
				+ "        \"is_duplicate_verification_failed\": false,\r\n"
				+ "        \"is_client_import\": false,\r\n"
				+ "        \"concurrent_save_allowed\": true,\r\n"
				+ "        \"owner\": {\r\n"
				+ "            \"id\": 6621248345538560,\r\n"
				+ "            \"domain\": \"yadavshubham4567\",\r\n"
				+ "            \"email\": RandomEmail,\r\n"
				+ "            \"phone\": \"\",\r\n"
				+ "            \"name\": \"Shubham\",\r\n"
				+ "            \"pic\": \"https://d1gwclp1pmzk26.cloudfront.net/img/gravatar/48.png\",\r\n"
				+ "            \"schedule_id\": \"Shubham\",\r\n"
				+ "            \"calendar_url\": \"https://yadavshubham4567.agilecrm.com/calendar/Shubham\",\r\n"
				+ "            \"calendarURL\": \"https://yadavshubham4567.agilecrm.com/calendar/Shubham\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"id\": 6705553621057536,\r\n"
				+ "        \"type\": \"PERSON\",\r\n"
				+ "        \"created_time\": 1762491371,\r\n"
				+ "        \"updated_time\": 0,\r\n"
				+ "        \"last_contacted\": 0,\r\n"
				+ "        \"last_emailed\": 0,\r\n"
				+ "        \"last_campaign_emaild\": 0,\r\n"
				+ "        \"last_called\": 0,\r\n"
				+ "        \"viewed_time\": 0,\r\n"
				+ "        \"viewed\": {\r\n"
				+ "            \"viewed_time\": 1762491688169,\r\n"
				+ "            \"viewer_id\": 6621248345538560\r\n"
				+ "        },\r\n"
				+ "        \"star_value\": 0,\r\n"
				+ "        \"lead_score\": 0,\r\n"
				+ "        \"klout_score\": \"\",\r\n"
				+ "        \"tags\": [\r\n"
				+ "            \"tester\",\r\n"
				+ "            \"qa\",\r\n"
				+ "            \"manual tester\"\r\n"
				+ "        ],\r\n"
				+ "        \"tagsWithTime\": [\r\n"
				+ "            {\r\n"
				+ "                \"tag\": \"tester\",\r\n"
				+ "                \"createdTime\": 1762491371169,\r\n"
				+ "                \"availableCount\": 0,\r\n"
				+ "                \"entity_type\": \"tag\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"tag\": \"qa\",\r\n"
				+ "                \"createdTime\": 1762491371169,\r\n"
				+ "                \"availableCount\": 0,\r\n"
				+ "                \"entity_type\": \"tag\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"tag\": \"manual tester\",\r\n"
				+ "                \"createdTime\": 1762491371169,\r\n"
				+ "                \"availableCount\": 0,\r\n"
				+ "                \"entity_type\": \"tag\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"properties\": [\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"first_name\",\r\n"
				+ "                \"value\": \"shubham\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"last_name\",\r\n"
				+ "                \"value\": \"QA \"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"company\",\r\n"
				+ "                \"value\": \"saritron\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"email\",\r\n"
				+ "                \"value\": \"yadavshubham@eva.com\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"phone\",\r\n"
				+ "                \"value\": \"1234567890\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"SYSTEM\",\r\n"
				+ "                \"name\": \"title\",\r\n"
				+ "                \"value\": \"Tester\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"campaignStatus\": [],\r\n"
				+ "        \"entity_type\": \"contact_entity\",\r\n"
				+ "        \"source\": \"manual\",\r\n"
				+ "        \"contact_company_id\": \"6434847133990912\",\r\n"
				+ "        \"unsubscribeStatus\": [],\r\n"
				+ "        \"emailBounceStatus\": [],\r\n"
				+ "        \"formId\": 0,\r\n"
				+ "        \"browserId\": [],\r\n"
				+ "        \"lead_source_id\": 0,\r\n"
				+ "        \"lead_status_id\": 0,\r\n"
				+ "        \"is_lead_converted\": false,\r\n"
				+ "        \"lead_converted_time\": 0,\r\n"
				+ "        \"is_duplicate_existed\": false,\r\n"
				+ "        \"trashed_time\": 0,\r\n"
				+ "        \"restored_time\": 0,\r\n"
				+ "        \"is_duplicate_verification_failed\": false,\r\n"
				+ "        \"is_client_import\": false,\r\n"
				+ "        \"concurrent_save_allowed\": true,\r\n"
				+ "        \"owner\": {\r\n"
				+ "            \"id\": 6621248345538560,\r\n"
				+ "            \"domain\": \"yadavshubham4567\",\r\n"
				+ "            \"email\": \"yadavshubham@eva.com\",\r\n"
				+ "            \"phone\": \"\",\r\n"
				+ "            \"name\": \"Shubham\",\r\n"
				+ "            \"pic\": \"https://d1gwclp1pmzk26.cloudfront.net/img/gravatar/48.png\",\r\n"
				+ "            \"schedule_id\": \"Shubham\",\r\n"
				+ "            \"calendar_url\": \"https://yadavshubham4567.agilecrm.com/calendar/Shubham\",\r\n"
				+ "            \"calendarURL\": \"https://yadavshubham4567.agilecrm.com/calendar/Shubham\"\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "]";
		
		Response resp =RestAssured.given().auth().basic("yadavshubham@eva.com", "Shubham@1234").contentType(ContentType.JSON).accept(ContentType.JSON).body(ContactJson).post("yadavshubham4567.agilecrm.com/dev/api/contacts");
		int stcode=resp.getStatusCode();
		long respTime=resp.time();
		String responseJsonString=resp.getBody().asPrettyString();
		
		if(stcode==200) {
			System.out.println("passed   "+stcode);
		}else {
			System.out.println("failed   "+stcode);
		}
		
		
		if(respTime>2000) {
			System.out.println("failed   "+ respTime);
		}else {
		System.out.println("passed    "+ respTime);	
		}
		
		
		Number expectedStarValue=9;
		JSONObject  jso = new JSONObject(responseJsonString);
		Number actualStarValue=jso.getNumber("star_value");
		if(actualStarValue==expectedStarValue) {
			System.out.println("passed");
		}else {
			System.out.println("failed");
		}
		
		
	}
}
